### ISSUE TITLE
Tabset works but style is different 

### ISSUE THREAD

**Issue by cderv** [rstudio/rsformat#2]
![image](https://user-images.githubusercontent.com/6791940/115874789-d3053f80-a444-11eb-9891-1bef38208bc8.png)

Original is : 
![image](https://user-images.githubusercontent.com/6791940/115874841-e2848880-a444-11eb-9051-c6fd27d4d2aa.png)

Could this be change ?

**Comment by cderv** [comment]
This is related to #8 : the `bs3compat.js`file is required for tabset to works as expected: 

How to check ? 

Run a document with theme less bs3compat layer
```yaml
output:
  html_document:
    self_contained: false
    theme: !expr bslib::bs_remove(bslib::bs_theme(version = 4), "bs3compat")
```

This will lead to the same first style shown above
