### ISSUE TITLE
Conflict with bslib 

### ISSUE THREAD

**Issue by cderv** [rstudio/rsformat#8]
Currently this assumes that we use bslib to activate bootstrap version 4 and we just replace the bootstrap dependency with the one from rstrap.

However **bslib** also adds other dependency - one being `bs3compat`

Currently the order of dependency cause this issue
```js
Uncaught TypeError: Cannot read property 'Constructor' of undefined
    at bs3compat.js:11
    at bs3compat.js:44
```

This is because rstrap will not replace bootstrap files from bslib but will be loaded as a new dependency with same name but higher version **after** the bslib one. This cause a failure due to order of dependency. 

We need to remove b3compat or change the order.

Note: bslib will load bootstrap.bundle.js and not just bootstrap.js - not sure if that matters.

**Comment by cderv** [comment]
And this is what is causing the issue with #2 - it requires a compatibility level with BS3 and it seems it does not work correctly.

How to check ? 

Run a document with theme less bs3compat layer
```yaml
output:
  html_document:
    self_contained: false
    theme: !expr bslib::bs_remove(bslib::bs_theme(version = 4), "bs3compat")
```
